onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top/clk
add wave -noupdate /top/uart_if_inst/clk
add wave -noupdate -radix unsigned /top/uart_if_inst/din
add wave -noupdate -radix unsigned /top/uart_if_inst/dout
add wave -noupdate /top/uart_if_inst/wr_en
add wave -noupdate /top/uart_if_inst/reset
add wave -noupdate /top/uart_if_inst/tx_busy
add wave -noupdate /top/uart_if_inst/ready
add wave -noupdate /top/uart_if_inst/cb/dout
add wave -noupdate /top/uart_if_inst/cb/ready
add wave -noupdate /top/uart_if_inst/cb/tx_busy
add wave -noupdate /top/uart_if_inst/cb/wr_en
add wave -noupdate /top/uart_if_inst/cb/din
add wave -noupdate /top/uart_if_inst/cb/cb_event
add wave -noupdate /top/uart_if_inst/mcb/dout
add wave -noupdate /top/uart_if_inst/mcb/ready
add wave -noupdate /top/uart_if_inst/mcb/tx_busy
add wave -noupdate /top/uart_if_inst/mcb/reset
add wave -noupdate /top/uart_if_inst/mcb/wr_en
add wave -noupdate /top/uart_if_inst/mcb/din
add wave -noupdate /top/uart_if_inst/mcb/mcb_event
add wave -noupdate /top/test_uart/din
add wave -noupdate /top/test_uart/wr_en
add wave -noupdate /top/test_uart/clk
add wave -noupdate /top/test_uart/reset
add wave -noupdate /top/test_uart/tx_busy
add wave -noupdate /top/test_uart/ready
add wave -noupdate /top/test_uart/dout
add wave -noupdate /top/test_uart/rx_en
add wave -noupdate /top/test_uart/tx_en
add wave -noupdate /top/test_uart/tx_rx
add wave -noupdate /top/test_uart/uart_baud/clk
add wave -noupdate /top/test_uart/uart_baud/rx_en
add wave -noupdate /top/test_uart/uart_baud/tx_en
add wave -noupdate /top/test_uart/uart_baud/rx_acc
add wave -noupdate /top/test_uart/uart_baud/tx_acc
add wave -noupdate /top/test_uart/uart_tx/din
add wave -noupdate /top/test_uart/uart_tx/wr_en
add wave -noupdate /top/test_uart/uart_tx/clk
add wave -noupdate /top/test_uart/uart_tx/clk_en
add wave -noupdate /top/test_uart/uart_tx/tx
add wave -noupdate /top/test_uart/uart_tx/tx_busy
add wave -noupdate /top/test_uart/uart_tx/data
add wave -noupdate /top/test_uart/uart_tx/bit_pos
add wave -noupdate /top/test_uart/uart_tx/state
add wave -noupdate /top/test_uart/uart_rx/rx
add wave -noupdate /top/test_uart/uart_rx/clk
add wave -noupdate /top/test_uart/uart_rx/clk_en
add wave -noupdate /top/test_uart/uart_rx/reset
add wave -noupdate /top/test_uart/uart_rx/ready
add wave -noupdate /top/test_uart/uart_rx/dout
add wave -noupdate /top/test_uart/uart_rx/state
add wave -noupdate /top/test_uart/uart_rx/sample
add wave -noupdate /top/test_uart/uart_rx/bit_pos
add wave -noupdate /top/test_uart/uart_rx/op_reg
add wave -noupdate /top/tb_inst/vif/clk
add wave -noupdate /top/tb_inst/vif/din
add wave -noupdate /top/tb_inst/vif/wr_en
add wave -noupdate /top/tb_inst/vif/reset
add wave -noupdate /top/tb_inst/vif/tx_busy
add wave -noupdate /top/tb_inst/vif/ready
add wave -noupdate /top/tb_inst/vif/dout
add wave -noupdate /top/tb_inst/vif/cb/dout
add wave -noupdate /top/tb_inst/vif/cb/ready
add wave -noupdate /top/tb_inst/vif/cb/tx_busy
add wave -noupdate /top/tb_inst/vif/cb/wr_en
add wave -noupdate /top/tb_inst/vif/cb/din
add wave -noupdate /top/tb_inst/vif/cb/cb_event
add wave -noupdate /top/tb_inst/vif/mcb/dout
add wave -noupdate /top/tb_inst/vif/mcb/ready
add wave -noupdate /top/tb_inst/vif/mcb/tx_busy
add wave -noupdate /top/tb_inst/vif/mcb/reset
add wave -noupdate /top/tb_inst/vif/mcb/wr_en
add wave -noupdate /top/tb_inst/vif/mcb/din
add wave -noupdate /top/tb_inst/vif/mcb/mcb_event
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {215552 ns}
